# -*- coding: utf-8 -*-
"""Naprawa #2: podmiana uszkodzonego bloku przez zakres linii (UTF-8, polskie znaki)."""
import ast

PATH = "Postac_program_gui.py"
lines = open(PATH, encoding="utf-8").read().split("\n")

assert lines[3262] == "        else:", repr(lines[3262])
assert lines[3372] == "    def create_experience_tab(self) -> None:", repr(lines[3372])

clean_lines = [
    '        else:',
    '            for category_name, title in (',
    '                (SKILL_CATEGORY_BASIC, "Podstawowe"),',
    '                (SKILL_CATEGORY_ADVANCED, "Zaawansowane / grupowe"),',
    '            ):',
    '                entries = grouped_skill_entries[category_name]',
    '                if not entries:',
    '                    continue',
    '                ctk.CTkLabel(',
    '                    single_column,',
    '                    text=title,',
    '                    font=FONT_BODY_BOLD,',
    '                    text_color=COLOR_TEXT_MUTED,',
    '                ).pack(anchor="w", padx=6, pady=(6, 2))',
    '                for skill_name, skill_data in entries:',
    '                    self._build_cost_row(',
    '                        single_column,',
    '                        self._format_skill_display_name(skill_name),',
    '                        skill_data["advanced"],',
    '                        "umiejetnosc",',
    '                        get_skill_category_short(skill_name),',
    '                        skill_data["initial"] + skill_data["advanced"],',
    '                    )',
    '',
    '    def on_add_skill_dialog(self) -> None:',
    '        """Okno dodawania nowej umiej\u0119tno\u015bci (przeniesione z osobnej zak\u0142adki)."""',
    '        dialog = ctk.CTkToplevel(self)',
    '        dialog.title("Dodaj umiej\u0119tno\u015b\u0107")',
    '        dialog.geometry("520x360")',
    '        dialog.transient(self)',
    '        dialog.grab_set()',
    '',
    '        ctk.CTkLabel(dialog, text="Nazwa umiej\u0119tno\u015bci:", font=FONT_BODY_BOLD).pack(',
    '            anchor="w", padx=16, pady=(16, 2)',
    '        )',
    '        name_entry = ctk.CTkEntry(',
    '            dialog, width=480, height=34,',
    '            placeholder_text="np. Bro\u0144 Bia\u0142a (Kawaleryjska)",',
    '        )',
    '        name_entry.pack(padx=16, pady=(0, 8))',
    '',
    '        ctk.CTkLabel(dialog, text="Atrybut:", font=FONT_BODY_BOLD).pack(',
    '            anchor="w", padx=16, pady=(0, 2)',
    '        )',
    '        attr_combo = ctk.CTkComboBox(dialog, values=ATTRIBUTES, width=480)',
    '        attr_combo.set("")',
    '        attr_combo.pack(padx=16, pady=(0, 8))',
    '',
    '        ctk.CTkLabel(dialog, text="Rozwini\u0119cia:", font=FONT_BODY_BOLD).pack(',
    '            anchor="w", padx=16, pady=(0, 2)',
    '        )',
    '        advanced_entry = ctk.CTkEntry(dialog, width=120, height=34)',
    '        advanced_entry.insert(0, "0")',
    '        advanced_entry.pack(anchor="w", padx=16, pady=(0, 8))',
    '',
    '        ctk.CTkLabel(',
    '            dialog,',
    '            text="Warto\u015b\u0107 pocz\u0105tkowa b\u0119dzie r\u00f3wna warto\u015bci przypisanej cechy.",',
    '            text_color=COLOR_TEXT_MUTED,',
    '            font=FONT_SMALL,',
    '            wraplength=480,',
    '            justify="left",',
    '        ).pack(anchor="w", padx=16, pady=(0, 8))',
    '',
    '        def confirm() -> None:',
    '            skill_name = name_entry.get().strip()',
    '            attribute = attr_combo.get()',
    '            validation_error = self._validate_skill_form(skill_name, attribute)',
    '            if validation_error:',
    '                messagebox.showerror("B\u0142\u0105d", validation_error, parent=dialog)',
    '                return',
    '            try:',
    '                advanced = int(advanced_entry.get())',
    '            except ValueError:',
    '                messagebox.showerror("B\u0142\u0105d", "Warto\u015b\u0107 numeryczna musi by\u0107 liczb\u0105.", parent=dialog)',
    '                return',
    '            if advanced < 0:',
    '                messagebox.showerror("B\u0142\u0105d", "Liczba rozwini\u0119\u0107 nie mo\u017ce by\u0107 ujemna.", parent=dialog)',
    '                return',
    '            dialog.destroy()',
    '            self._create_skill(skill_name, attribute, advanced)',
    '',
    '        button_row = ctk.CTkFrame(dialog, fg_color="transparent")',
    '        button_row.pack(fill="x", padx=16, pady=(8, 16))',
    '        ctk.CTkButton(',
    '            button_row, text="Dodaj", command=confirm, fg_color=COLOR_SUCCESS, width=120',
    '        ).pack(side="right", padx=(8, 0))',
    '        ctk.CTkButton(',
    '            button_row, text="Anuluj", command=dialog.destroy,',
    '            fg_color=COLOR_SURFACE_SOFT, hover_color="#48505e", width=120,',
    '        ).pack(side="right")',
    '',
    '    def _create_skill(self, skill_name: str, attribute: str, advanced: int) -> None:',
    '        """Dodaje umiej\u0119tno\u015b\u0107 do postaci i od\u015bwie\u017ca widoki."""',
    '        initial = self.data_manager.attributes[attribute]["initial"]',
    '        self.data_manager.add_skill(skill_name, attribute, initial, advanced, is_new=True)',
    '        self.pending_changes["new_skills"].add(skill_name)',
    '',
    '        self.history_manager.add_entry(',
    '            "Dodano umiej\u0119tno\u015b\u0107",',
    '            f"{skill_name} ({attribute}) - Pocz: {initial}, Rozw: {advanced}",',
    '        )',
    '        messagebox.showinfo("Sukces", f"Umiej\u0119tno\u015b\u0107 \'{skill_name}\' dodana!")',
    '',
    '        self.initialized_skills = False',
    '        self.cost_options_dirty = True',
    '        self.initialize_skills_display()',
    '        self.refresh_history_display()',
    '        self.refresh_costs_if_visible(force=True)',
]

new_lines = lines[:3262] + clean_lines + lines[3372:]
open(PATH, "w", encoding="utf-8").write("\n".join(new_lines))
print("BLOCK REPLACED")

try:
    ast.parse(open(PATH, encoding="utf-8").read())
    print("SYNTAX OK")
except SyntaxError as e:
    print(f"NEXT ERROR line {e.lineno}: {e.msg}")
